### ISSUE TITLE
프로젝트와 관련 없는 디렉토리 삭제

### ISSUE THREAD

**Issue by jay4peace** [lsirikh/memaker_fine_dust_purifier#1]
[.settings](https://github.com/lsirikh/memaker_fine_dust_purifier/tree/master/tizen-iot/.settings)
[.sign](https://github.com/lsirikh/memaker_fine_dust_purifier/tree/master/tizen-iot/.sign)
[crash-info](https://github.com/lsirikh/memaker_fine_dust_purifier/tree/master/tizen-iot/crash-info)
[.vs](https://github.com/lsirikh/memaker_fine_dust_purifier/tree/master/tizen-iot/src/.vs)

**Comment by lsirikh** [comment]
삭제 완료 했습니다.
