### ISSUE TITLE
Indentation 및 로그 수정

### ISSUE THREAD

**Issue by eylee928** [lsirikh/memaker_fine_dust_purifier#10]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/c4ae63ee811926c6e29c7d42465748a4ee4497d8/tizen-iot/src/ai2c.cpp#L363-L366

- 들여쓰기 수정
- 로그에서 %s가 없어도 될 것 같습니다.

**Comment by lsirikh** [comment]
수정하였습니다.

**Comment by eylee928** [comment]
_E("cannot add a timer(%s)", "Cannot register ecore timer for thingspark data transmission");

위 로그에서 %s를 사용하실 필요가 없습니다.
위 로그를 찍고 싶으시다면 아래와 같이 고쳐주세요. 

_E("cannot add a timer("Cannot register ecore timer for thingspark data transmission)");

**Comment by lsirikh** [comment]
수정했습니다.
