### ISSUE TITLE
timer 관련 로그 수정

### ISSUE THREAD

**Issue by eylee928** [lsirikh/memaker_fine_dust_purifier#11]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/c4ae63ee811926c6e29c7d42465748a4ee4497d8/tizen-iot/src/ai2c.cpp#L336

타이머를 %d로 찍는 것이 이상합니다. 
필요하시다면 %p로 주소값을 찍으시거나, 필요 없으면 해당로그는 삭제해주세요.

**Comment by lsirikh** [comment]
수정하였습니다.
