### ISSUE TITLE
strdup() 후 메모리 정리

### ISSUE THREAD

**Issue by eylee928** [lsirikh/memaker_fine_dust_purifier#13]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/c4ae63ee811926c6e29c7d42465748a4ee4497d8/tizen-iot/src/thingspark.c#L95-L96

위 코드는 timer에 의해 30초에  한 번씩 실행되면서 strdup()가 호출될 때마다 메모리를 계속 할당합니다. 에러가 리턴되었을 때 메모리 정리가 필요합니다.

**Comment by lsirikh** [comment]
tp_initialize 과 tp_finalize은
 ai2c.cpp의 _get_sensor_value함수에서
 라이프사이클을 갖습니다. 
제가 잘못 알고 있는 것이면 추가적인 설명 부탁드립니다.

**Comment by eylee928** [comment]
정상적인 경우 30초에 한 번씩 _get_sensor_value (timer callback func)가 호출되면
tp_initialize에 의해 메모리가 할당되고,
tp_finalize에 의해 메모리가 해제됩니다.

하지만 메모리가 할당된 이후 비정상적으로 앱이 종료될 시 메모리가 제대로 해제되지 않기 때문에
_get_sensor_value가 다시 호출되었을 경우 사용하지 않는 메모리 값이 쌓이게 됩니다.

비정상적으로 종료될 경우에 strdup()로 할당된 메모리를 해제해주시는게 좋습니다.

**Comment by lsirikh** [comment]
예상하지 못한 중단이 발생하는 경우 어느 부분에 해제 코드를 적용하는 것이 좋을지 조언 부탁드립니다.

**Comment by eylee928** [comment]
예를들어 아래 코드에서 예상치못한 에러가 나서 리턴이 된다면

	ret = tp_set_field_value(handle, 1, PM10);
	retv_if(ret != 0, -1);

retv_if(ret != 0, -1) 대신 goto_if(ret != 0, error);를 써서 
아래와 같이 처리하면 어떨까요?

error:
        free_resource(......);
        return -1;


강의 때 실습한 apps/native/rcc를 참고하시면 goto문 이용한 부분이 있을 겁니다.
참고하세요.

**Comment by lsirikh** [comment]
수정했습니다. 확인 부탁드립니다.
