### ISSUE TITLE
return value를 ECORE_CALLBACK_CANCEL로 수정

### ISSUE THREAD

**Issue by eylee928** [lsirikh/memaker_fine_dust_purifier#14]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/4aeba18160fd9026704d1d778fcf13b789de1b9f/tizen-iot/src/ai2c.cpp#L248

_get_sensor_value는 timer callback func이고 return 타입이 Eina_Bool입니다.
error가 발생했을 시 return 타입을 ECORE_CALLBACK_CANCEL(0)으로 해주세요.

**Comment by lsirikh** [comment]
수정했습니다.

**Comment by eylee928** [comment]
_get_sensor_value() 내의 다른 retv_if들도 고쳐주세요.

**Comment by lsirikh** [comment]
수정을 했는데 여기에 커멘트 다는 걸 깜빡했습니다.^^

**Comment by eylee928** [comment]
ERROR 문에서 
return -1;도 return ECORE_CALLBACK_CANCEL;로 바꿔주세요.

**Comment by lsirikh** [comment]
수정반영했습니다. 그리고 기존에 불필요한 c파일과 2개의 헤더파일을 삭제 정리했습니다.

**Comment by lsirikh** [comment]
ERROR 문 이후에 return ECORE_CALLBACK_RENEW; 로 변경 했습니다.
혹시 추가로 더 변경이 필요하거나 보완하야할 사항이 있으시면 말씀해주세요.
