### ISSUE TITLE
사용하지 않는 변수 삭제

### ISSUE THREAD

**Issue by jay4peace** [lsirikh/memaker_fine_dust_purifier#2]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/52e644515758ce281560f372449ded2e33aba1ad/tizen-iot/src/resource/resource_AI2C.c#L52

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/52e644515758ce281560f372449ded2e33aba1ad/tizen-iot/src/resource/resource_AI2C.c#L104

**Comment by lsirikh** [comment]
사용하는 변수로 바꿨습니다.

**Comment by jay4peace** [comment]
write는 언제나 0인데 왜 필요한지 잘 모르겠습니다. 변수와 조건문이 필요 없어 보이네요.

**Comment by lsirikh** [comment]
그러네요. 말씀하신것처럼 삭제하였습니다.
