### ISSUE TITLE
변수 타입과 사이즈 확인 필요

### ISSUE THREAD

**Issue by jay4peace** [lsirikh/memaker_fine_dust_purifier#3]
`out_value`, `input_value`의 타입이 `unsigned int` 이어야 할 것 같습니다. 
또 array 사이즈를 명시적으로 선언하거나, 함수 내부에서 체크 해야 할 것 같습니다.

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/52e644515758ce281560f372449ded2e33aba1ad/tizen-iot/src/resource/resource_AI2C.c#L49

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/52e644515758ce281560f372449ded2e33aba1ad/tizen-iot/src/resource/resource_AI2C.c#L101

**Comment by theojin** [comment]
int resource_write_arduino(int i2c_bus, int *input_value)
위의 함수는 내부적으로 int -> uint8_t로 변환하고 있습니다.
 	cbuf[0] = (uint8_t)input_value[0];//set commnand for number in arduino
	cbuf[1] = (uint8_t)input_value[1];//set commnand for value in arduino

아예, 함수에서 uint8_t를 인자로 받는 것은 어떨까요?
int resource_write_arduino(int i2c_bus, uint8_t *input_value)

**Comment by lsirikh** [comment]
int resource_read_arduino(int i2c_bus, int *out_value) 
 int *out_value --> uint16_t로 수정하였습니다.
 int resource_write_arduino(int i2c_bus, int *input_value) 
 int *out_value --> uint8_t로 수정하였습니다.

**Comment by jay4peace** [comment]
변수 타입만 수정되고 array 사이즈에 대한 체크는 반영되지 않은 것 같습니다.

**Comment by lsirikh** [comment]
좀 더 구체적으로 말씀해주실 수 있을까요?

**Comment by jay4peace** [comment]
`int resource_read_arduino(int i2c_bus, int *out_value) ` 함수의 구현 내용을 보면 `out_value`는 size 5짜리 배열이어야 합니다. 하지만 함수의 prototype만 보고는 그 사실을 알 수가 없습니다. 
이런 제약 사항이 있는 parameter는 prototype에서 명확히 알 수 있도록 해주셔야합니다.

**Comment by lsirikh** [comment]
네 수정했습니다.  의도에 맞게 된지 모르겠습니다. 그 외 다른 분도 같이 수정했습니다.

**Comment by jay4peace** [comment]
함수의 정의가 수정되어야 한다는 말인데, 다른 부분을 수정하신듯 하네요.

**Comment by lsirikh** [comment]
수정했습니다. 확인 부탁드립니다.
