### ISSUE TITLE
전역 변수 또는 핸들을 일관성 있게 사용

### ISSUE THREAD

**Issue by jay4peace** [lsirikh/memaker_fine_dust_purifier#4]
[tizen-iot/src/ai2c.cpp](https://github.com/lsirikh/memaker_fine_dust_purifier/blob/master/tizen-iot/src/ai2c.cpp) 파일의 전역 변수와 app_data 구조체가 혼용되고 있음. 일관되게 한가지만으로 사용하면 좋겠습니다.

전역 변수를 사용할 경우 모두 scope을 `static`으로 변경하면 좋겠습니다.

**Comment by lsirikh** [comment]
무슨 말인지 제가 잘 이해를 못하는 것 같습니다. app_data 의 역할이 정확하게 어떻게 되는지 설명 부탁드립니다.

**Comment by jay4peace** [comment]
app_data를 사용하는 원래의 취지는 전역변수를 사용하지 않고 main함수 내의 로컬 변수로 선언하고 콜백 함수의 data 핸들로 받아서 해당 메모리에 접근하여 사용하도록 하는 것입니다.
구현하신 것처럼 전역 변수에 직접 접근하여 쓰시려고 하면 굳이 app data를 만들지 않고 쓰시거나, 아니면 전역변수들을 app data에 넣어 핸들로 관리하는 두가지 방법 중에 한가지로 일관성있게 코드를 통일하면 좋겠습니다.

**Comment by lsirikh** [comment]
// app_data를 활용하여 app간 호출 시 참조 변수 활용
static app_data *g_ad = NULL;
삭제했습니다.
또한, main쪽 도 함께 수정하였습니다.

**Comment by jay4peace** [comment]
https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L52
`static const char` 이어야 합니다.

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L56
이 변수가 왜 전역 변수여야 하나요? 전역 변수여야 한다면 `static const char` 이어야 합니다. 

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L59
이 변수가 왜 전역 변수여야 하나요? 전역 변수여야 한다면 `static int`이어야 합니다. 

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L72-L74
포인터 하나만을 위한 구조체가 왜 필요한가요?

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L77
전역 변수여야 한다면 `static Ecore_Timer *`이여야 합니다.

https://github.com/lsirikh/memaker_fine_dust_purifier/blob/27236c7259b3dad0c37b0fa7a68f19a5620977cd/tizen-iot/src/ai2c.cpp#L88
전역 변수여야 한다면,  `static uint16_t`이어야 합니다.

앞서도 말씀드렸지만, 필요한 변수들을 모두 전역 변수로 쓰던지, 핸들로 만들어 쓰던지 한가지로 통일 해주시고, 전역 변수로 쓰실 때는 꼭 scope을 한정해주세요.

**Comment by lsirikh** [comment]
전체적으로 수정했습니다. 확인 부탁드리겠습니다.
