### ISSUE TITLE
thingspark의 api-key 노출

### ISSUE THREAD

**Issue by theojin** [lsirikh/memaker_fine_dust_purifier#6]
api-key는 개인에게 부여한 키이기 때문에 노출하지 않는게 좋지 않을까요?
"현재 프로그램에 적용된 thingspark와 연동되는 코드 부분"
위의 부분에 명시되어 있습니다.

**Comment by lsirikh** [comment]
#으로 표사하여 수정하였습니다.

**Comment by theojin** [comment]
감사합니다~!
