### ISSUE TITLE
시인성을 위한 switch문 사용

### ISSUE THREAD

**Issue by theojin** [lsirikh/memaker_fine_dust_purifier#7]
if(get_value==0){
				valueSet[1]=get_value;
			}else if(get_value==1){
				valueSet[1]=get_value;
			}else if(get_value==2){
				valueSet[1]=get_value;
			}else if(get_value==3){
				valueSet[1]=get_value;
			}else if(get_value==4){
				valueSet[1]=get_value;
			}else if(get_value==5){
				valueSet[1]=get_value;
			}

위의 소스는 switch 문으로 하는게 좀 더 시인성이 좋지 않을까요?

**Comment by lsirikh** [comment]
불필요한 조건문을 삭제하였고, 간소화 했습니다.

**Comment by theojin** [comment]
네, 감사합니다.
