### ISSUE TITLE
Nubison 인식키 삭제

### ISSUE THREAD

**Issue by theojin** [lsirikh/memaker_fine_dust_purifier#8]
코드 중에,
// Nubison 클라우드에서 발급하는 인식키
// 연결장치의 제품 식별키를 입력하기
char mytoken[32] = "xxxxxxx"
위의 부분은 노출하지 않는 것이 어떨까요?

**Comment by lsirikh** [comment]
#으로 수정하여 표시하였습니다.

**Comment by theojin** [comment]
감사합니다~!
