### ISSUE TITLE
명시적인 버퍼 사이즈

### ISSUE THREAD

**Issue by theojin** [lsirikh/memaker_fine_dust_purifier#9]
uint8_t buf[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};//read data buffer
	uint32_t length = 10; //buffer byte length

	uint8_t cbuf[] = { 0x00, 0x00, 0x00, 0x00 };//command buffer
	uint32_t length = 2; //buffer byte length

차후에 buf만 수정하고 length를 수정하지 않을 위험이 있으니,
Buf size는 명시적으로 지정하는 것은 어떨까요?

**Comment by lsirikh** [comment]
명시적으로 변경하였습니다.
READ_BUFFER 10
WRITE_BUFFER 2

**Comment by theojin** [comment]
네, 감사합니다.
